force-app/main/default/objects/Developer__c/fields/Especialidade__c.field-meta.xml
<CustomField>
    <fullName>Especialidade__c</fullName>
    <label>Especialidade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Developer_Allocation__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Developer Allocations</relationshipLabel>
    <relationshipName>Developer_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Developer_Allocation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Developer Allocations</relationshipLabel>
    <relationshipName>Developer_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeveloperAllocationControllerTest.cls
@isTest
private class DeveloperAllocationControllerTest {
    @isTest static void testAllocateDevelopers() {
        Developer__c d = new Developer__c(Name='Dev One', Especialidade__c='Salesforce', Email__c='dev@example.com');
        insert d;
        Account a = new Account(Name='ACME');
        insert a;
        Opportunity o = new Opportunity(Name='Opp Dev', StageName='Qualificação', CloseDate=Date.today(), AccountId=a.Id);
        insert o;

        Test.startTest();
            DeveloperAllocationController.allocateDevelopers(o.Id, new List<Id>{d.Id}, Date.today(), Date.today().addDays(30));
        Test.stopTest();

        Integer countAlloc = [SELECT count() FROM Developer_Allocation__c WHERE Opportunity__c = :o.Id];
        System.assertEquals(1, countAlloc);
    }
}